### ISSUE TITLE
META 1.9 release

### ISSUE THREAD

**Issue by michalbiesek** [memkind/memkind#184]
The issue is created to track planned 1.9 release features:

- [x] extend API to support detecting kind - ref #172
- [x] extend API to support memory management in PMEM kind ref #175
- [x] add benchmark to measure different memory management in PMEM kind #199
- [x] cleanup README and INSTALL - ref #171
